periodics:
- interval: 10m
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  dimaunx/submariner:
  - name: test-postsubmit
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  dimaunx/submariner:
  - name: test-presubmit
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]