---
- name: Create VM on RDO Cloud
  os_server:
    state: present
    name: "{{ item }}"
    auth:
      auth_url: "{{ auth_url }}"
      password: "{{ os_password }}"
      project_domain_id: "{{ project_domain_id }}"
      project_name: "{{ project_name }}"
      username: "{{ username }}"
      user_domain_name: "{{ user_domain_name }}"
    image: fdfd5d39-a76d-45df-abec-17f768ba3054
    key_name: "dfarrell standard"
    network: private_k8s_net
    security_groups:
      - ssh_icmp
    flavor_ram: 4096
  with_items:
    - toolbox
