---
- name: Install openshift-install
  unarchive:
    # NB: This will expire periodically
    # TODO: Find more stable install method
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.1.0-rc.3.tar.gz
    remote_src: yes
    dest: /usr/local/bin/
    mode: 0755
  become: yes

- name: Create AWS config dir
  file:
    path: .aws
    state: directory

- name: Instantiate RH AWS credentials template to AWS config dir
  template:
    src: aws-credentials-template.j2
    dest: ".aws/credentials"

- name: Copy RH AWS config to AWS config dir
  copy:
    src: aws-config
    dest: ".aws/config"
